import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import { getCurrentSession } from '@/actions/auth';
import { SanityLive } from "@/sanity/lib/live";
import HeaderCategorySelector from "@/components/layout/HeaderCategorySelector";
import Cart from "@/components/cart/Cart";
import Script from "next/script";
import { Suspense } from "react";
import AnalyticsTracker from "@/components/layout/AnalyticsTracker";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await getCurrentSession();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header 
          user={user} 
          categorySelector={<HeaderCategorySelector />}        
        />
        <Script
          src='https://cloud.umami.is/script.js'
          data-website-id='28b7a145-25d2-42c7-99d5-730e72c9a414'
          strategy='beforeInteractive'
        />
        {children}

        <Suspense>
          <AnalyticsTracker
            user={user}
          />
        </Suspense>

        <Cart />
        
        <SanityLive />
      </body>
    </html>
  );
}
